"""nullable cards

Revision ID: 3659353a08f8
Revises: cd344088994c
Create Date: 2024-01-08 23:00:58.701420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3659353a08f8'
down_revision: Union[str, None] = 'cd344088994c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('ev_title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('ev_tags',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('ev_text',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('note_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('note_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('note_tags',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('note_tags',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('note_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('note_title',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('ev_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('ev_tags',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('ev_title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
