"""Init

Revision ID: 6f74605af717
Revises: 033607dbb8e3
Create Date: 2023-11-23 20:42:31.242759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f74605af717'
down_revision: Union[str, None] = '033607dbb8e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('ev_datetime', sa.DateTime(), nullable=True))
    op.drop_column('events', 'ev_date')
    op.drop_column('events', 'ev_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('ev_time', sa.TIME(), nullable=True))
    op.add_column('events', sa.Column('ev_date', sa.DATE(), nullable=True))
    op.drop_column('events', 'ev_datetime')
    # ### end Alembic commands ###
