"""init postgres

Revision ID: b069fd8404ab
Revises: 
Create Date: 2024-01-07 00:24:32.558840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b069fd8404ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_tg_id', sa.Integer(), nullable=False),
    sa.Column('tg_username', sa.String(length=250), nullable=False),
    sa.Column('tg_full_name', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_tg_id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_tg_id', sa.Integer(), nullable=False),
    sa.Column('ev_datetime', sa.DateTime(), nullable=False),
    sa.Column('ev_title', sa.String(length=100), nullable=False),
    sa.Column('ev_tags', sa.String(), nullable=False),
    sa.Column('ev_text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_tg_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_tg_id', sa.Integer(), nullable=False),
    sa.Column('note_title', sa.String(), nullable=False),
    sa.Column('note_text', sa.String(), nullable=False),
    sa.Column('note_tags', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_tg_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('screenshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_tg_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=100), nullable=False),
    sa.Column('hashtags', sa.String(), nullable=False),
    sa.Column('caption', sa.String(), nullable=False),
    sa.Column('ocr_text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_tg_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_tg_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_tg_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_tg_id', sa.Integer(), nullable=False),
    sa.Column('user_timezone', sa.String(length=20), nullable=False),
    sa.Column('ai_platform', sa.String(length=50), nullable=False),
    sa.Column('ai_api_key', sa.String(length=100), nullable=False),
    sa.Column('calendar_event_duration', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_tg_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_table('sessions')
    op.drop_table('screenshots')
    op.drop_table('notes')
    op.drop_table('events')
    op.drop_table('users')
    # ### end Alembic commands ###
