"""nullable cards

Revision ID: fea4db29f075
Revises: cd344088994c
Create Date: 2024-01-08 22:18:59.117199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fea4db29f075'
down_revision: Union[str, None] = 'cd344088994c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'ev_title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('events', 'ev_tags',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('events', 'ev_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('notes', 'note_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('notes', 'note_text',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('notes', 'note_tags',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'note_tags',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('notes', 'note_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('notes', 'note_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('events', 'ev_text',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('events', 'ev_tags',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('events', 'ev_title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
